{
 "title": "Central At Hand Tecnologia",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "NOVOS",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id = 1;"
    }
   ]
  },
  {
   "title": "ABERTOS",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (1,4);"
    }
   ]
  },
  {
   "title": "LEMBRETE",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (6);"
    }
   ]
  },
  {
   "title": "AGENDAMENTOS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select \n   title as TÍTULO,start_time as INÍCIO,end_time AS FIM \nfrom\n   calendar_appointment ca\n   where start_time >= now() ;"
    }
   ]
  },
  {
   "title": "CHAMADOS POR EMPRESA",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "select\n\tcc.customer_id as \"CLIENTE\", \n\tcount(t.id) as \"TICKETS\"\nfrom\n\tticket t,\n\tqueue q,\n\tticket_state ts,\n\tcustomer_company cc\nwhere\n\tt.customer_id = cc.customer_id and\n\tt.queue_id = q.id and\n\tt.ticket_state_id = ts.id and\n\tt.ticket_state_id in (1,4,6,7,8,11,12,13,14) and\n\tq.name <> 'Lixo' \ngroup by\n\tcc.customer_id\norder by \n\tTICKETS desc;\n"
    }
   ]
  },
  {
   "title": "CHAMADOS POR ATENDENTE",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "select\r\n \r\n  u.login as Atendente,\r\n \r\n  count(t.id) Chamados\r\n\r\nfrom\r\n \r\n  ticket t,\r\n \r\n  queue q,\r\n \r\n  users u\r\n \r\nwhere\r\n \r\n  u.id = t.responsible_user_id and\r\n \r\n  q.id = t.queue_id and\r\n\r\n   t.ticket_state_id in (1,4,6,7,8) and\r\n \r\n  q.id in (5,6,10,7,8,9)\r\n\r\ngroup by u.login;"
    }
   ]
  },
  {
   "title": "SLA VENCIDO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select \n\n\tt.tn as TICKET,\n\tt.title as TÍTULO, \n\ts.name as SLA, \n\tq.name as FILA,\n\tt.create_time as ABERTURA\n\n\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tsla s\nwhere \n\tt.queue_id = q.id and \n\tt.ticket_state_id = ts.id and\n\tt.sla_id = s.id and \n\tq.name <> 'Lixo' and \n\tts.id not in (2,3,10) and \n\tfrom_unixtime(t.escalation_time) < NOW() and \n  t.escalation_time > 0;"
    }
   ]
  }
 ]
}